services:
  geofencing:
    build: ./Geofencing-Microservice
    ports:
      - "5001:5001"
    depends_on:
      - keyauthority
    command: gunicorn -w 4 --preload -b 0.0.0.0:5001 app:app

  keyauthority:
    build: ./KeyAuthority-Microservice
    ports:
      - "5002:5002"
    command: gunicorn -w 4 --preload -b 0.0.0.0:5002 app:app

